name: Build Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build image
        run: docker build -f ./Dockerfile -t alexandre3gomes/haproxy .
      - name: Push image to registry
        run: docker push alexandre3gomes/haproxy
